spring:
  webflux:
    base-path: /movies
  profiles:
    active: local
  data:
    mongodb:
      uri: ${MONGO_DB_CONNECTION_STRING}
      database: reactive-ms
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 8082
management:
  endpoints:
    web:
      base-path: /_manage
      exposure:
        include: "*"
#logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
spring:
  webflux:
    base-path: /movies
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      uri: ${MONGO_DB_CONNECTION_STRING}
      database: reactive-ms

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG

